// Generated by npm run catalog:generate. Do not edit by hand.
import type { Theme } from "@/lib/themes";

export const GENERATED_THEMES = [
  {
    "slug": "dilraba-star",
    "name": "Dilraba Star",
    "summary": "星光蓝紫与甜酷舞台氛围，包含真实背景、Logo、首页引导与四张快捷操作卡。",
    "author": {
      "name": "Codex Skin",
      "handle": "codex-skin",
      "curated": true
    },
    "category": "gradient",
    "platforms": [
      "macos",
      "windows"
    ],
    "colors": [
      "violet",
      "blue"
    ],
    "tags": [
      "真实主题",
      "星光",
      "人物",
      "甜酷",
      "双平台"
    ],
    "stats": {
      "downloads": 0,
      "rating": 0,
      "reviews": 0
    },
    "featured": true,
    "isNew": true,
    "version": "1.0.0",
    "engineRange": ">=1.0.0 <2.0.0",
    "publishedAt": "2026-07-17T06:00:00.000Z",
    "license": {
      "name": "Codex-Skin Theme Assets",
      "spdx": "LicenseRef-Codex-Skin-Theme",
      "source": "project-curated-assets"
    },
    "package": {
      "published": true,
      "id": "dilraba-star",
      "version": "1.0.0",
      "url": "https://github.com/lixiaobaivv/Codex-Skin/releases/download/official-themes-v1/Codex-Skin-theme-dilraba-star-1.0.0.dreamskin",
      "sha256": "45eed254d3ecbc13e2c13cb0efbde3678594ec290683d6db641893aca61ffe17",
      "size": 1015797
    },
    "previewImage": "/theme-previews/dilraba-star.png",
    "previewStyle": {
      "backgroundColor": "#f4f1ff",
      "backgroundImage": "linear-gradient(#f4f1ff, #ece6ff)",
      "panelColor": "#f4f1ff",
      "panelBorder": "#c7b8ef",
      "textColor": "#151b72",
      "mutedTextColor": "#7476a1",
      "accentColor": "#7b49ff",
      "accentSoft": "#e6dcff",
      "codeColor": "#b459ff",
      "shadow": "0 28px 80px rgba(21,27,114,.22)",
      "pattern": "stars"
    }
  },
  {
    "slug": "enfp-pop",
    "name": "ENFP Pop",
    "summary": "高饱和青橙与自由脑暴氛围，面向快速原型、灵感探索和轻快创作。",
    "author": {
      "name": "Codex Skin",
      "handle": "codex-skin",
      "curated": true
    },
    "category": "editorial",
    "platforms": [
      "macos",
      "windows"
    ],
    "colors": [
      "teal",
      "orange"
    ],
    "tags": [
      "真实主题",
      "ENFP",
      "脑暴",
      "高饱和",
      "双平台"
    ],
    "stats": {
      "downloads": 0,
      "rating": 0,
      "reviews": 0
    },
    "featured": false,
    "isNew": true,
    "version": "1.0.0",
    "engineRange": ">=1.0.0 <2.0.0",
    "publishedAt": "2026-07-17T06:00:00.000Z",
    "license": {
      "name": "Codex-Skin Theme Assets",
      "spdx": "LicenseRef-Codex-Skin-Theme",
      "source": "project-curated-assets"
    },
    "package": {
      "published": true,
      "id": "enfp-pop",
      "version": "1.0.0",
      "url": "https://github.com/lixiaobaivv/Codex-Skin/releases/download/official-themes-v1/Codex-Skin-theme-enfp-pop-1.0.0.dreamskin",
      "sha256": "b9f9b08b2707a83c4b404c4dc98d82334baa0b01e5c3c44fda3554d7438da336",
      "size": 956764
    },
    "previewImage": "/theme-previews/enfp-pop.png",
    "previewStyle": {
      "backgroundColor": "#fffaf0",
      "backgroundImage": "linear-gradient(#fffaf0, #fff0dc)",
      "panelColor": "#fffaf0",
      "panelBorder": "#efcfae",
      "textColor": "#202335",
      "mutedTextColor": "#77726d",
      "accentColor": "#12bfa5",
      "accentSoft": "#d7f5ef",
      "codeColor": "#ffb31a",
      "shadow": "0 28px 80px rgba(255,106,87,.2)",
      "pattern": "paper"
    }
  },
  {
    "slug": "jackson-sage",
    "name": "Jackson Sage",
    "summary": "鼠尾草绿与安静留白氛围，完整呈现真实首页背景、品牌元素和引导文案。",
    "author": {
      "name": "Codex Skin",
      "handle": "codex-skin",
      "curated": true
    },
    "category": "nature",
    "platforms": [
      "macos",
      "windows"
    ],
    "colors": [
      "green",
      "neutral"
    ],
    "tags": [
      "真实主题",
      "人物",
      "鼠尾草",
      "留白",
      "双平台"
    ],
    "stats": {
      "downloads": 0,
      "rating": 0,
      "reviews": 0
    },
    "featured": true,
    "isNew": true,
    "version": "1.0.0",
    "engineRange": ">=1.0.0 <2.0.0",
    "publishedAt": "2026-07-17T06:00:00.000Z",
    "license": {
      "name": "Codex-Skin Theme Assets",
      "spdx": "LicenseRef-Codex-Skin-Theme",
      "source": "project-curated-assets"
    },
    "package": {
      "published": true,
      "id": "jackson-sage",
      "version": "1.0.0",
      "url": "https://github.com/lixiaobaivv/Codex-Skin/releases/download/official-themes-v1/Codex-Skin-theme-jackson-sage-1.0.0.dreamskin",
      "sha256": "d737eb406bcb8612c6ff4814a2e9644287617dcc23d78fa99b2f698cb02c4abd",
      "size": 1233340
    },
    "previewImage": "/theme-previews/jackson-sage.png",
    "previewStyle": {
      "backgroundColor": "#f6f4ea",
      "backgroundImage": "linear-gradient(#f6f4ea, #e8eddd)",
      "panelColor": "#f6f4ea",
      "panelBorder": "#bdc8aa",
      "textColor": "#3d4a31",
      "mutedTextColor": "#777d70",
      "accentColor": "#879966",
      "accentSoft": "#e3e9d8",
      "codeColor": "#b99b68",
      "shadow": "0 28px 80px rgba(61,74,49,.2)",
      "pattern": "mist"
    }
  },
  {
    "slug": "kun-stage",
    "name": "KUN Stage",
    "summary": "黑金舞台与聚光灯氛围，使用真实主题背景、Logo 和完整首页引导内容。",
    "author": {
      "name": "Codex Skin",
      "handle": "codex-skin",
      "curated": true
    },
    "category": "dark",
    "platforms": [
      "macos",
      "windows"
    ],
    "colors": [
      "black",
      "orange"
    ],
    "tags": [
      "真实主题",
      "人物",
      "黑金",
      "舞台",
      "双平台"
    ],
    "stats": {
      "downloads": 0,
      "rating": 0,
      "reviews": 0
    },
    "featured": false,
    "isNew": true,
    "version": "1.0.0",
    "engineRange": ">=1.0.0 <2.0.0",
    "publishedAt": "2026-07-17T06:00:00.000Z",
    "license": {
      "name": "Codex-Skin Theme Assets",
      "spdx": "LicenseRef-Codex-Skin-Theme",
      "source": "project-curated-assets"
    },
    "package": {
      "published": true,
      "id": "kun-stage",
      "version": "1.0.0",
      "url": "https://github.com/lixiaobaivv/Codex-Skin/releases/download/official-themes-v1/Codex-Skin-theme-kun-stage-1.0.0.dreamskin",
      "sha256": "5b6be40451f7b9d69daca1c36d85b5f1115054ddf3cac61c27606f500cad5d7e",
      "size": 1115718
    },
    "previewImage": "/theme-previews/kun-stage.png",
    "previewStyle": {
      "backgroundColor": "#101211",
      "backgroundImage": "linear-gradient(#101211, #050606)",
      "panelColor": "#101211",
      "panelBorder": "#4b4436",
      "textColor": "#ead8b5",
      "mutedTextColor": "#9b927f",
      "accentColor": "#d5b47c",
      "accentSoft": "#352f25",
      "codeColor": "#d5b47c",
      "shadow": "0 28px 80px rgba(0,0,0,.55)",
      "pattern": "embers"
    }
  },
  {
    "slug": "user-upload-test",
    "name": "我的第一个主题",
    "summary": "一个清晰、舒适，适合日常使用的 Codex 主题。",
    "author": {
      "name": "lixiaobai",
      "handle": "lixiaobaivv",
      "curated": false
    },
    "category": "nature",
    "platforms": [
      "macos",
      "windows"
    ],
    "colors": [
      "blue"
    ],
    "tags": [
      "社区主题",
      "浅色",
      "双平台"
    ],
    "stats": {
      "downloads": 0,
      "rating": 0,
      "reviews": 0
    },
    "featured": false,
    "isNew": true,
    "version": "1.0.0",
    "engineRange": ">=1.0.0 <2.0.0",
    "publishedAt": "2026-07-17T15:55:14.729Z",
    "license": {
      "name": "Codex-Skin Theme Assets",
      "spdx": "LicenseRef-Codex-Skin-Theme",
      "source": "project-curated-assets"
    },
    "package": null,
    "previewImage": "/theme-previews/user-upload-test.png",
    "previewStyle": {
      "backgroundColor": "#f7f6f2",
      "backgroundImage": "linear-gradient(145deg, #f7f6f2, #dddbff)",
      "panelColor": "#f7f6f2",
      "panelBorder": "#070709",
      "textColor": "#20212a",
      "mutedTextColor": "#131318",
      "accentColor": "#635bff",
      "accentSoft": "#dddbff",
      "codeColor": "#635bff",
      "shadow": "0 28px 80px #36328c55",
      "pattern": "mist"
    }
  },
  {
    "slug": "zhu-xudan-racing",
    "name": "Zhu Xudan Racing",
    "summary": "赛车红黑与卡丁车疾速氛围，包含人物背景、竞速 Logo、首页引导与四张快捷操作卡。",
    "author": {
      "name": "Codex Skin",
      "handle": "codex-skin",
      "curated": true
    },
    "category": "dark",
    "platforms": [
      "macos",
      "windows"
    ],
    "colors": [
      "rose",
      "orange",
      "black"
    ],
    "tags": [
      "祝绪丹",
      "人物",
      "赛车",
      "卡丁车",
      "深色",
      "双平台"
    ],
    "stats": {
      "downloads": 0,
      "rating": 0,
      "reviews": 0
    },
    "featured": false,
    "isNew": true,
    "version": "1.0.0",
    "engineRange": ">=1.0.0 <2.0.0",
    "publishedAt": "2026-07-17T08:11:01.000Z",
    "license": {
      "name": "Codex-Skin Theme Assets",
      "spdx": "LicenseRef-Codex-Skin-Theme",
      "source": "project-curated-assets"
    },
    "package": {
      "published": true,
      "id": "zhu-xudan-racing",
      "version": "1.0.0",
      "url": "https://github.com/lixiaobaivv/Codex-Skin/releases/download/official-themes-v2/Codex-Skin-theme-zhu-xudan-racing-1.0.0.dreamskin",
      "sha256": "9da9d441fe42723f536d2edc30fb87b35ec93cbbc8f4e13d148ec4898e245ac0",
      "size": 3083241
    },
    "previewImage": "/theme-previews/zhu-xudan-racing.png",
    "previewStyle": {
      "backgroundColor": "#17191e",
      "backgroundImage": "linear-gradient(135deg, #0d0f12, #2a1718)",
      "panelColor": "#17191e",
      "panelBorder": "#4a2a2b",
      "textColor": "#f7f4ef",
      "mutedTextColor": "#b9b3ad",
      "accentColor": "#e53935",
      "accentSoft": "#4a1f20",
      "codeColor": "#ffb020",
      "shadow": "0 28px 80px rgba(0,0,0,.42)",
      "pattern": "embers"
    }
  }
] as const satisfies readonly Theme[];
