// Generated by npm run catalog:generate. Do not edit by hand.
import type { Theme } from "@/lib/themes";

export const GENERATED_THEMES = [
  {
    "slug": "aurora-drift",
    "name": "极光漫游",
    "summary": "蓝紫极光缓缓掠过深夜，为长时间创作保留恰到好处的层次。",
    "author": {
      "name": "Northlight Studio",
      "handle": "northlight",
      "curated": true
    },
    "category": "gradient",
    "platforms": [
      "macos",
      "windows"
    ],
    "colors": [
      "violet",
      "blue",
      "black"
    ],
    "tags": [
      "极光",
      "冷色",
      "夜间",
      "渐变"
    ],
    "stats": {
      "downloads": 28430,
      "rating": 4.9,
      "reviews": 816
    },
    "featured": true,
    "isNew": false,
    "version": "1.3.0",
    "engineRange": ">=1.1.0 <2.0.0",
    "publishedAt": "2026-04-18T08:00:00.000Z",
    "license": {
      "name": "CC0 1.0 Universal",
      "spdx": "CC0-1.0",
      "source": "original-procedural-artwork"
    },
    "previewStyle": {
      "backgroundColor": "#080b18",
      "backgroundImage": "radial-gradient(circle at 72% 18%, rgba(110, 231, 255, .5), transparent 32%), radial-gradient(circle at 30% 8%, rgba(167, 139, 250, .58), transparent 38%), linear-gradient(145deg, #17112f 0%, #081426 48%, #071015 100%)",
      "panelColor": "rgba(11, 17, 33, .78)",
      "panelBorder": "rgba(172, 205, 255, .16)",
      "textColor": "#f4f7ff",
      "mutedTextColor": "#9aa9c6",
      "accentColor": "#8be8ff",
      "accentSoft": "rgba(139, 232, 255, .16)",
      "codeColor": "#c4b5fd",
      "shadow": "0 28px 80px rgba(3, 7, 20, .48)",
      "pattern": "aurora"
    },
    "package": null
  },
  {
    "slug": "ember-terminal",
    "name": "余烬终端",
    "summary": "炭黑背景中留下一点琥珀余温，为终端爱好者打造的低干扰主题。",
    "author": {
      "name": "Afterdark Tools",
      "handle": "afterdark",
      "curated": false
    },
    "category": "dark",
    "platforms": [
      "macos",
      "windows"
    ],
    "colors": [
      "black",
      "orange"
    ],
    "tags": [
      "终端",
      "炭黑",
      "琥珀",
      "夜间"
    ],
    "stats": {
      "downloads": 3670,
      "rating": 4.7,
      "reviews": 96
    },
    "featured": false,
    "isNew": true,
    "version": "1.0.0",
    "engineRange": ">=1.2.0 <2.0.0",
    "publishedAt": "2026-07-12T08:00:00.000Z",
    "license": {
      "name": "CC0 1.0 Universal",
      "spdx": "CC0-1.0",
      "source": "original-procedural-artwork"
    },
    "previewStyle": {
      "backgroundColor": "#0f0d0c",
      "backgroundImage": "radial-gradient(circle at 77% 8%, rgba(239, 133, 55, .23), transparent 30%), linear-gradient(145deg, #171311, #0b0a09 64%)",
      "panelColor": "rgba(20, 17, 15, .92)",
      "panelBorder": "rgba(231, 159, 87, .17)",
      "textColor": "#f4eee7",
      "mutedTextColor": "#a69a8f",
      "accentColor": "#e9a35b",
      "accentSoft": "rgba(233, 163, 91, .13)",
      "codeColor": "#f1bd76",
      "shadow": "0 28px 74px rgba(0, 0, 0, .48)",
      "pattern": "embers"
    },
    "package": null
  },
  {
    "slug": "jackson-sage-signed-sample",
    "name": "千玺星球签名示例",
    "summary": "首个可真实下载的双平台签名样例，用同一份信任契约验证 Windows 与 macOS 导入流程。",
    "author": {
      "name": "Codex-Skin contributors",
      "handle": "codex-skin",
      "curated": true
    },
    "category": "nature",
    "platforms": [
      "macos",
      "windows"
    ],
    "colors": [
      "green",
      "neutral",
      "orange"
    ],
    "tags": [
      "签名示例",
      "双平台",
      "Ed25519",
      "开源"
    ],
    "stats": {
      "downloads": 0,
      "rating": 5,
      "reviews": 0
    },
    "featured": true,
    "isNew": true,
    "version": "1.0.0",
    "engineRange": ">=1.0.0 <2.0.0",
    "publishedAt": "2026-07-16T12:00:00.000Z",
    "license": {
      "name": "CC0 1.0 Universal",
      "spdx": "CC0-1.0",
      "source": "original-procedural-artwork"
    },
    "package": {
      "published": true,
      "id": "codex-skin.jackson-sage-sample",
      "version": "1.0.0",
      "url": "https://github.com/lixiaobaivv/Codex-Skin/releases/download/sample-v1/codex-skin-sample-1.0.0.dreamskin",
      "sha256": "7a75fff8086fe6949ef9e37e82c161a8e015a1e00e02181938cd479e9ae41387",
      "size": 2041227
    },
    "previewStyle": {
      "backgroundColor": "#cbd7ca",
      "backgroundImage": "radial-gradient(circle at 80% 12%, rgba(215, 180, 106, .5), transparent 24%), linear-gradient(145deg, #dfe8dc, #78937b 55%, #516b54)",
      "panelColor": "rgba(244, 245, 239, .86)",
      "panelBorder": "rgba(81, 107, 84, .22)",
      "textColor": "#1d2a20",
      "mutedTextColor": "#647066",
      "accentColor": "#516b54",
      "accentSoft": "rgba(81, 107, 84, .14)",
      "codeColor": "#9d694f",
      "shadow": "0 28px 72px rgba(29, 42, 32, .24)",
      "pattern": "mist"
    }
  },
  {
    "slug": "linen-light",
    "name": "亚麻晨光",
    "summary": "温柔米白与细腻纸纤维质感，让界面像一本摊开的轻盈笔记。",
    "author": {
      "name": "Quiet Form",
      "handle": "quietform",
      "curated": true
    },
    "category": "minimal",
    "platforms": [
      "macos"
    ],
    "colors": [
      "neutral",
      "orange"
    ],
    "tags": [
      "浅色",
      "米白",
      "极简",
      "纸张"
    ],
    "stats": {
      "downloads": 14720,
      "rating": 4.7,
      "reviews": 391
    },
    "featured": false,
    "isNew": false,
    "version": "1.0.6",
    "engineRange": ">=1.1.0 <2.0.0",
    "publishedAt": "2026-02-11T08:00:00.000Z",
    "license": {
      "name": "CC0 1.0 Universal",
      "spdx": "CC0-1.0",
      "source": "original-procedural-artwork"
    },
    "previewStyle": {
      "backgroundColor": "#eee8dc",
      "backgroundImage": "radial-gradient(circle at 18% 0%, rgba(255, 255, 255, .88), transparent 38%), repeating-linear-gradient(96deg, rgba(107, 91, 65, .025) 0 1px, transparent 1px 6px)",
      "panelColor": "rgba(255, 253, 248, .84)",
      "panelBorder": "rgba(95, 76, 51, .13)",
      "textColor": "#332e27",
      "mutedTextColor": "#817666",
      "accentColor": "#a55e2f",
      "accentSoft": "rgba(165, 94, 47, .11)",
      "codeColor": "#7c4a2e",
      "shadow": "0 24px 60px rgba(79, 63, 38, .16)",
      "pattern": "paper"
    },
    "package": null
  },
  {
    "slug": "midnight-grid",
    "name": "午夜网格",
    "summary": "精密网格与克制的电光蓝，适合偏爱结构感的深色工作台。",
    "author": {
      "name": "Plain Systems",
      "handle": "plainsystems",
      "curated": true
    },
    "category": "dark",
    "platforms": [
      "macos",
      "windows"
    ],
    "colors": [
      "black",
      "blue"
    ],
    "tags": [
      "网格",
      "深色",
      "蓝黑",
      "技术感"
    ],
    "stats": {
      "downloads": 19680,
      "rating": 4.8,
      "reviews": 504
    },
    "featured": true,
    "isNew": false,
    "version": "1.1.2",
    "engineRange": ">=1.0.0 <2.0.0",
    "publishedAt": "2026-03-02T08:00:00.000Z",
    "license": {
      "name": "CC0 1.0 Universal",
      "spdx": "CC0-1.0",
      "source": "original-procedural-artwork"
    },
    "previewStyle": {
      "backgroundColor": "#080a0f",
      "backgroundImage": "linear-gradient(rgba(72, 113, 170, .1) 1px, transparent 1px), linear-gradient(90deg, rgba(72, 113, 170, .1) 1px, transparent 1px), radial-gradient(circle at 78% 12%, rgba(50, 126, 255, .2), transparent 35%)",
      "panelColor": "rgba(13, 17, 24, .92)",
      "panelBorder": "rgba(100, 142, 204, .2)",
      "textColor": "#eef4ff",
      "mutedTextColor": "#8491a5",
      "accentColor": "#65a5ff",
      "accentSoft": "rgba(101, 165, 255, .14)",
      "codeColor": "#8cc8ff",
      "shadow": "0 26px 70px rgba(0, 0, 0, .5)",
      "pattern": "grid"
    },
    "package": null
  },
  {
    "slug": "moss-and-mist",
    "name": "苔色山雾",
    "summary": "层叠苔绿与清晨薄雾，营造沉静、有呼吸感的专注空间。",
    "author": {
      "name": "Field Notes Lab",
      "handle": "fieldnotes",
      "curated": true
    },
    "category": "nature",
    "platforms": [
      "macos",
      "windows"
    ],
    "colors": [
      "green",
      "neutral",
      "black"
    ],
    "tags": [
      "森林",
      "雾",
      "绿色",
      "沉静"
    ],
    "stats": {
      "downloads": 8720,
      "rating": 4.9,
      "reviews": 219
    },
    "featured": false,
    "isNew": true,
    "version": "1.0.1",
    "engineRange": ">=1.2.0 <2.0.0",
    "publishedAt": "2026-07-03T08:00:00.000Z",
    "license": {
      "name": "CC0 1.0 Universal",
      "spdx": "CC0-1.0",
      "source": "original-procedural-artwork"
    },
    "previewStyle": {
      "backgroundColor": "#17221d",
      "backgroundImage": "radial-gradient(ellipse at 28% 20%, rgba(207, 222, 202, .34), transparent 35%), linear-gradient(155deg, rgba(75, 101, 76, .9), rgba(25, 40, 32, .94) 48%, #101714 100%)",
      "panelColor": "rgba(20, 31, 25, .76)",
      "panelBorder": "rgba(183, 210, 182, .15)",
      "textColor": "#eef4eb",
      "mutedTextColor": "#9dad9e",
      "accentColor": "#a9cf9b",
      "accentSoft": "rgba(169, 207, 155, .14)",
      "codeColor": "#c3dda7",
      "shadow": "0 28px 72px rgba(7, 14, 10, .42)",
      "pattern": "mist"
    },
    "package": null
  },
  {
    "slug": "ocean-glass",
    "name": "海面玻璃",
    "summary": "清透海岸色调叠加磨砂玻璃面板，明亮但不刺眼。",
    "author": {
      "name": "Tidal Workshop",
      "handle": "tidalworkshop",
      "curated": false
    },
    "category": "nature",
    "platforms": [
      "macos",
      "windows"
    ],
    "colors": [
      "teal",
      "blue",
      "neutral"
    ],
    "tags": [
      "海洋",
      "玻璃",
      "青蓝",
      "明亮"
    ],
    "stats": {
      "downloads": 11390,
      "rating": 4.8,
      "reviews": 284
    },
    "featured": true,
    "isNew": false,
    "version": "1.2.1",
    "engineRange": ">=1.1.0 <2.0.0",
    "publishedAt": "2026-05-06T08:00:00.000Z",
    "license": {
      "name": "CC0 1.0 Universal",
      "spdx": "CC0-1.0",
      "source": "original-procedural-artwork"
    },
    "previewStyle": {
      "backgroundColor": "#9ed7dc",
      "backgroundImage": "linear-gradient(175deg, rgba(235, 249, 246, .9) 0 30%, rgba(91, 187, 197, .58) 31% 55%, rgba(21, 92, 121, .82) 80% 100%), radial-gradient(circle at 75% 28%, rgba(255, 255, 255, .7), transparent 18%)",
      "panelColor": "rgba(237, 251, 250, .68)",
      "panelBorder": "rgba(255, 255, 255, .46)",
      "textColor": "#163b45",
      "mutedTextColor": "#47727a",
      "accentColor": "#087f8c",
      "accentSoft": "rgba(8, 127, 140, .12)",
      "codeColor": "#075f72",
      "shadow": "0 28px 70px rgba(19, 80, 94, .22)",
      "pattern": "horizon"
    },
    "package": null
  },
  {
    "slug": "paper-observatory",
    "name": "纸上天文台",
    "summary": "深蓝墨色与细小星图铺在暖灰纸面上，像一本安静的观测手册。",
    "author": {
      "name": "Margin Press",
      "handle": "marginpress",
      "curated": true
    },
    "category": "editorial",
    "platforms": [
      "macos"
    ],
    "colors": [
      "neutral",
      "blue",
      "black"
    ],
    "tags": [
      "星图",
      "纸张",
      "编辑风",
      "复古"
    ],
    "stats": {
      "downloads": 5230,
      "rating": 4.8,
      "reviews": 127
    },
    "featured": true,
    "isNew": true,
    "version": "1.0.2",
    "engineRange": ">=1.2.0 <2.0.0",
    "publishedAt": "2026-07-08T08:00:00.000Z",
    "license": {
      "name": "CC0 1.0 Universal",
      "spdx": "CC0-1.0",
      "source": "original-procedural-artwork"
    },
    "previewStyle": {
      "backgroundColor": "#c9c2b3",
      "backgroundImage": "radial-gradient(circle at 13% 19%, rgba(30, 46, 69, .55) 0 1px, transparent 2px), radial-gradient(circle at 72% 28%, rgba(30, 46, 69, .42) 0 1px, transparent 2px), repeating-linear-gradient(0deg, rgba(56, 48, 38, .025) 0 1px, transparent 1px 5px)",
      "panelColor": "rgba(240, 236, 226, .86)",
      "panelBorder": "rgba(37, 49, 67, .18)",
      "textColor": "#202c3d",
      "mutedTextColor": "#697080",
      "accentColor": "#284d7a",
      "accentSoft": "rgba(40, 77, 122, .12)",
      "codeColor": "#513f64",
      "shadow": "0 24px 64px rgba(49, 45, 39, .2)",
      "pattern": "stars"
    },
    "package": null
  },
  {
    "slug": "solar-bloom",
    "name": "日光绽放",
    "summary": "珊瑚橙与玫瑰粉相遇，给工作区注入温暖又现代的能量。",
    "author": {
      "name": "Chromatic Dept.",
      "handle": "chromaticdept",
      "curated": false
    },
    "category": "gradient",
    "platforms": [
      "windows"
    ],
    "colors": [
      "orange",
      "rose",
      "violet"
    ],
    "tags": [
      "暖色",
      "日落",
      "活力",
      "渐变"
    ],
    "stats": {
      "downloads": 6940,
      "rating": 4.6,
      "reviews": 168
    },
    "featured": false,
    "isNew": true,
    "version": "1.0.0",
    "engineRange": ">=1.2.0 <2.0.0",
    "publishedAt": "2026-06-27T08:00:00.000Z",
    "license": {
      "name": "CC0 1.0 Universal",
      "spdx": "CC0-1.0",
      "source": "original-procedural-artwork"
    },
    "previewStyle": {
      "backgroundColor": "#7f284d",
      "backgroundImage": "radial-gradient(circle at 70% 22%, rgba(255, 222, 130, .88), transparent 24%), radial-gradient(circle at 30% 72%, rgba(238, 103, 139, .72), transparent 40%), linear-gradient(145deg, #4d2b82, #bc3f6b 48%, #ee8c52)",
      "panelColor": "rgba(72, 27, 64, .7)",
      "panelBorder": "rgba(255, 229, 207, .23)",
      "textColor": "#fff8f4",
      "mutedTextColor": "#f2c6c3",
      "accentColor": "#ffd68d",
      "accentSoft": "rgba(255, 214, 141, .17)",
      "codeColor": "#ffc6a5",
      "shadow": "0 28px 80px rgba(65, 17, 50, .38)",
      "pattern": "orb"
    },
    "package": null
  }
] as const satisfies readonly Theme[];
