import { readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { loadCatalog } from "./validate-catalog.mjs";

const ROOT = fileURLToPath(new URL("../", import.meta.url));
const outputPath = join(ROOT, "lib", "generated-themes.ts");
const themes = await loadCatalog();
const output = `// Generated by npm run catalog:generate. Do not edit by hand.\nimport type { Theme } from "@/lib/themes";\n\nexport const GENERATED_THEMES = ${JSON.stringify(themes, null, 2)} as const satisfies readonly Theme[];\n`;

if (process.argv.includes("--check")) {
  const current = await readFile(outputPath, "utf8").catch(() => "");
  if (current !== output) {
    console.error("lib/generated-themes.ts is stale. Run npm run catalog:generate and commit the result.");
    process.exitCode = 1;
  }
} else {
  await writeFile(outputPath, output);
  console.log(`Generated ${themes.length} themes in lib/generated-themes.ts.`);
}
